DROP TABLE IF EXISTS grocery_list;
DROP TABLE IF EXISTS home_inventory;
DROP TABLE IF EXISTS grocery_users;

CREATE TABLE grocery_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  data_created TIMESTAMP NOT NULL DEFAULT now()
);

DROP TYPE IF EXISTS category;
CREATE TYPE category AS ENUM (
  'Produce',
  'Meat',
  'Poultry',
  'Dairy',
  'Dry Foods',
  'Frozen'
);

CREATE TABLE grocery_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  food_category category NOT NULL,
  shopper INTEGER REFERENCES grocery_users(id) NOT NULL
);

CREATE TABLE grocery_inventory (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  food_category category NOT NULL,
  shopper INTEGER REFERENCES grocery_users(id) NOT NULL
);